Traceback (most recent call last):
  File "train.py", line 101, in <module>
    print(net(th.rand((1,4,256*3,256*3)).to(device)))
  File "/hpc/home/diego.calanzone/.conda/envs/swe-cv-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hpc/scratch/diego.calanzone/diego.calanzone/video-prediction-numeric-simulations/models/ae/resnet_ae.py", line 83, in forward
    x = l(x)
  File "/hpc/home/diego.calanzone/.conda/envs/swe-cv-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hpc/scratch/diego.calanzone/diego.calanzone/video-prediction-numeric-simulations/models/ae/resnet_ae.py", line 33, in forward
    return self.activation(residual + y)
RuntimeError: The size of tensor a (383) must match the size of tensor b (379) at non-singleton dimension 3
